version: "3.8"

services:
  osrm:
    image: osrm/osrm-backend:latest
    container_name: osrm-sf
    ports:
      - "5050:5000"
    volumes:
      - ./data/osrm:/data
    command: osrm-routed --algorithm mld /data/sf.osrm
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: delivery-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: